spring:
  application:
    name: medalerta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
